version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "16686:16686"
    networks:
      - jaeger-demo

  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

  driver:
    build: ./driver
    ports: 
      - "8081:8081"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

  customer:
    build: ./customer
    ports: 
      - "8082:8082"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

  route:
    build: ./route
    ports: 
      - "8083:8083"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

  route-delay:
    build: ./route-delay
    ports: 
      - "8084:8084"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

  customer-delay:
    build: ./customer-delay
    ports: 
      - "8085:8085"
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

networks:
  jaeger-demo:
