version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-demo

  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

  driver:
    build: ./driver
    ports: 
      - "8081:8081"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-demo
    depends_on:
      - jaeger

networks:
  jaeger-demo:
